version: '3.7'
services:
    client:
        build:
            context: ./Web/ClientApp/
            dockerfile: Client.Dockerfile
        ports:
            - "3000:3000"
        depends_on:
            - "api"
    api:
        build:
            context: .
            dockerfile: Api.Dockerfile
        ports:
            - "8080:80"
        depends_on:
            - "db"
        environment: 
            - "ConnectionStrings__Todos=Server=172.18.0.2;Database=TodosDb;Username=postgres;Password=0905"
    db:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            - "POSTGRES_PASSWORD=0905"
         
